services:
  - type: web
    name: registro-escolar-v1-demo
    runtime: node
    plan: free
    buildCommand: npm run build && npm run db:deploy && cd app && npx prisma db seed
    startCommand: npm run start
    healthCheckPath: /login
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DEMO_PROFESSOR_EMAIL
        sync: false
      - key: DEMO_PROFESSOR_PASSWORD
        sync: false
      - key: NEXTAUTH_URL
        sync: false
